name: addressbook
description: Addressbook access for Flutter apps.
version: 1.0.0
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.skalio.addressbook
        pluginClass: AddressbookPlugin
      ios:
        pluginClass: AddressbookPlugin
      macos:
        pluginClass: AddressbookPlugin