name: addressbook
description: Addressbook access for Flutter apps.
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AddressbookPlugin
      macos:
        pluginClass: AddressbookPlugin
