name: addressbook
description: Addressbook access for Flutter apps.
version: 0.0.4
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.skalio.addressbook
        pluginClass: AddressbookPlugin
      ios:
        pluginClass: AddressbookPlugin
      macos:
        pluginClass: AddressbookPlugin