name: addressbook
description: Addressbook access for Flutter apps.
version: 1.1.2
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.skalio.addressbook
        pluginClass: AddressbookPlugin
      ios:
        pluginClass: AddressbookPlugin
      macos:
        pluginClass: AddressbookPlugin